apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: demo-client
spec:
  selector:
    matchLabels:
      name: demo-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: demo-client
    spec:
      containers:
      - env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: SERVER_PORT
          value: "50311"
        - name: RANDOM_SEED
          valueFrom:
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: IMAGE_PATHS
          value: "[]"
        - name: MODEL_IMAGE
          value: "mobilenet"
        - name: VIDEO
          value: "true"
        image: us-west1-docker.pkg.dev/soe-mlexray/pixie-development/koo-client:0.0.16
        imagePullPolicy: IfNotPresent
        name: app
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true 
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
