apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: demo-client
spec:
  replicas: 4
  selector:
    matchLabels:
      name: demo-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: demo-client
    spec:
      containers:
      - env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: SERVER_PORT
          value: "50311"
        - name: RANDOM_SEED
          valueFrom:
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MODEL_IMAGE
          value: "mobilenet"
        - name: IMAGE_PATHS
          value: '["https://upload.wikimedia.org/wikipedia/commons/b/b4/Samoyede_Nauka_2003-07_asb_PICT1895_small.JPG",
            "https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Sunflower_from_Silesia2.jpg/1600px-Sunflower_from_Silesia2.jpg"]'
        image: us-west1-docker.pkg.dev/soe-mlexray/pixie-development/koo-client:0.0.13
        imagePullPolicy: IfNotPresent
        name: app
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
